version: "3.9"
services:
  app:
    container_name: github-release-writer
    build:
      context: .
      args:
        nodeEnv: development
    ports:
      - 39410:39410
      - 39411:39411
    volumes:
      - ./dist/dockerVolume/config:/home/app/.config/github-release-writer
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"
