name: Publish Docker image
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: latest
            nodeEnv: production
          - tag: development
            nodeEnv: development
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jaidchen
          password: ${{ secrets.dockerHubToken }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/ppc64le
          tags: jaidchen/${{ github.event.repository.name }}:${{ matrix.tag }}
          build-args: nodeEnv=${{ matrix.nodeEnv }}
          cache-from: type=gha
          cache-to: type=gha,mode=max